# -*- coding: utf-8 -*-
"""Assignment 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f_qzK9FriIk579D8quyX8uwTDfxf8pPA
"""

#LetsUpgrade Assignment 1
#To build a calculator that does addition, subtraction, multplication and division

print("-----SIMPLE CALCULATOR-----")

print("Enter your first number : ")
x = int(input())
print("Enter your second number")
y = int(input())

add = x + y
sub = x - y
mul = x * y
div = x / y
print("Addition : ")
print(add)
print("Subtraction : ")
print(sub)
print("Multiplication : ")
print(mul)
print("Division : ")
print(div)

