# -*- coding: utf-8 -*-
"""Assignment_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fI312i-rJYZfXnCZmCMijTmvSq3E7GOM

Assignment 5 (1)

Build a function for finding if a number is prime or not.
"""

def prime(n):
    if (n==1):
        return False   #1 is not a prime number
    elif (n==2):
        return True;    #2 is always a prime number
    else:
        for i in range(2,n):    
            if(n % i==0):
                return False
        return True

prime(2)

prime(1)

prime(67)

prime(94)

"""Assignment 5(2)

Build  Youtube video Downloader App using library in Python refer pypi.org.

"""

pip install pytube

import pytube

url = 'https://youtu.be/3sZbFPDzUZU'

youtube = pytube.YouTube(url)
video = youtube.streams.first()
video.download('../Video')