# -*- coding: utf-8 -*-
"""PythonFinalProject1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UU-Y9RWCTrdsNp-gva7k36v2lHZlY2Re
"""

# 1
#Fetch The Weather of your city with the help of OWM api

pip install requests

import requests

api_key = "4256b3de394a56a86ee35e43af6f5c2e"

# ------- Getting the input from user -------

city = input("Enter the name of the city: ")

Data = requests.get(f"https://api.openweathermap.org/data/2.5/weather?q={city}&units=metric&APPID={api_key}")

# ------ Printing the Data ------
print(f"LOCATION: {Data.json().get('name')}, {Data.json().get('sys').get('country')}")
print(f"TEMPERATURE: {Data.json().get('main')['temp']}°C")
print(f"WEATHER: {Data.json().get('weather')[0].get('main')}")
print(
    f"MIN/MAX TEMPERATURE: {Data.json().get('main')['temp_min']}°C/{Data.json().get('main')['temp_max']}°C"
)
print(f"HUMIDITY: {Data.json().get('main')['humidity']}%")
print(f"WIND: {Data.json().get('wind')['speed']} km/h")